// Gemini: Generated by Gemini AI
using UnityEngine;

namespace SubmarineJourney.Core {
	public class GameStateService : MonoBehaviour {
		public static GameStateService instance { get; private set; }

		[Header("Global Status")]
		public float submarineDepth = 0f;
		public float totalSubmarineIntegrity = 100f;
		public float globalOxygenLevel = 1f;
		public float fuelLevel = 100f;

		[Header("Game Progress")]
		public bool isGamePaused = false;
		public float timePlayed = 0f;

		private void Awake() {
			if (instance == null) {
				instance = this;
			} else {
				Destroy(gameObject);
			}
		}

		private void Update() {
			if (!isGamePaused) {
				timePlayed += Time.deltaTime;
			}
		}
	}
}
