// Gemini: Generated by Gemini AI
using System;

namespace SubmarineJourney.Core {
	/// <summary>
	/// Atribut pro označení statických metod Init(), které mají být automaticky spuštěny při startu.
	/// </summary>
	[AttributeUsage(AttributeTargets.Method)]
	public class GlobalInitAttribute : Attribute { }
}
