// Gemini: Generated by Gemini AI
using UnityEngine;
using System;
using System.Reflection;

namespace SubmarineJourney.Core {
	public static class GlobalServiceInitializer {
		
		public static void InitializeServices() {
			Debug.Log("[GlobalServiceInitializer] Running attribute-based initialization...");

			var assembly = Assembly.GetExecutingAssembly();
			var types = assembly.GetTypes();

			foreach (var type in types) {
				if (type.Namespace == null || !type.Namespace.StartsWith("SubmarineJourney")) continue;

				var methods = type.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
				foreach (var method in methods) {
					if (method.IsDefined(typeof(GlobalInitAttribute), false)) {
						try {
							method.Invoke(null, null);
							Debug.Log($"[GlobalServiceInitializer] Invoked {type.Name}.{method.Name}");
						} catch (Exception e) {
							Debug.LogError($"[GlobalServiceInitializer] Failed to invoke {type.Name}: {e.Message}");
						}
					}
				}
			}
		}
	}
}
